language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t react_app -f Dockerfile.dev .

script:
  - docker run -e CI=true react_app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker_react"
  env: "Dockerreact-env"
  bucket_name: "Dockerreact-env.eba-ukdjj4va.eu-central-1.elasticbeanstalk.com"
  bucket_path: "docker_react"
  on:
    branch: master  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
